import { Poppins } from "next/font/google";
import { ClothingProvider } from "@/contexts/clothing";
import { Navbar } from "./components/navbar";
import Footer from "./components/Footer";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"], // Add additional subsets if needed
  weight: ["400", "500", "600", "700"], // Specify weights you need
});

export const metadata = {
  title: "Wardrobe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ClothingProvider>
          <Navbar />
          {children}
          <Footer />

          <Toaster />
        </ClothingProvider>
      </body>
    </html>
  );
}
