import { Poppins } from "next/font/google";
import { ClothingProvider } from "@/contexts/clothing";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"], // Add additional subsets if needed
  weight: ["400", "500", "600", "700"], // Specify weights you need
});

export const metadata = {
  title: "Wardrobe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ClothingProvider>{children}</ClothingProvider>
      </body>
    </html>
  );
}
